#!/usr/bin/env python3
"""
Generate static HTML "book" from selected Twitter threads, using chapter_titles.json overrides.

Key behaviors:
- Cover is book/index.html (content pulled from data/frontmatter/cover.html)
- Title page is book/chapters/title.html (from data/frontmatter/title.html)
- ToC is book/toc.html (generated), placed after title and before preface in reading order
- Preface is book/chapters/preface.html (from data/frontmatter/preface.html)
- "Noteworthy Singletons" is book/chapters/compendium.html (generated by separate compendium script)
- Thread chapters are generated as book/chapters/chapter_<thread_id>.html

Constraints:
- Does NOT overwrite book/style.css (so your manual CSS edits persist).
- Frontmatter fragment files are created ONLY if missing; rendered pages are updated every run.
- Thread chapters are always regenerated; frontmatter pages are regenerated; compendium is left intact
  but this script will patch its navigation bar if it finds it.

Optional:
- --run-cleanup invokes data/tweet_text_cleanup.py as a standalone script (if you want).
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from html import escape
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

DATA_DIR = ROOT / "data"
BOOK_DIR = ROOT / "book"
CHAPTERS_DIR = BOOK_DIR / "chapters"

THREADS_JSONL = DATA_DIR / "threads_data_ops_patched.jsonl"
TWEETS_JSONL = DATA_DIR / "tweets_normalized.jsonl"
SELECTION_JSON = DATA_DIR / "selection_final_clean.json"
CHAPTER_TITLES_JSON = DATA_DIR / "chapter_titles.json"

FRONT_DIR = DATA_DIR / "frontmatter"
COVER_FRAGMENT = FRONT_DIR / "cover.html"
TITLE_FRAGMENT = FRONT_DIR / "title.html"
PREFACE_FRAGMENT = FRONT_DIR / "preface.html"

STYLE_HREF_ROOT = "style.css"
STYLE_HREF_CHAPTER = "../style.css"

# Output paths
COVER_OUT = BOOK_DIR / "index.html"
TOC_OUT = BOOK_DIR / "toc.html"
TITLE_OUT = CHAPTERS_DIR / "title.html"
PREFACE_OUT = CHAPTERS_DIR / "preface.html"

SINGLETONS_TITLE = "Noteworthy Singletons"
TITLEPAGE_TITLE = "Title page"
PREFACE_TITLE = "Preface"


@dataclass
class Page:
    href: str
    title: str
    kind: str               # cover | title | toc | preface | singletons | thread
    chapter_no: Optional[int] = None
    subtitle: str = ""      # used for thread date subtitle


def iter_jsonl(path: Path):
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            yield json.loads(line)


def parse_created_at(s: str) -> Optional[datetime]:
    # Twitter created_at format: "Wed Oct 10 20:19:24 +0000 2018"
    if not s:
        return None
    try:
        # try strict twitter format
        return datetime.strptime(s, "%a %b %d %H:%M:%S %z %Y")
    except Exception:
        pass
    # fallback: ISO-ish
    try:
        dt = datetime.fromisoformat(s.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except Exception:
        return None


def format_long_date(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).strftime("%B %-d, %Y") if os.name != "nt" else dt.astimezone(timezone.utc).strftime("%B %#d, %Y")


def ensure_frontmatter_fragments():
    FRONT_DIR.mkdir(parents=True, exist_ok=True)

    if not COVER_FRAGMENT.exists():
        COVER_FRAGMENT.write_text(
            '<div class="cover">\n'
            '  <img class="cover-image" src="assets/cover.png" alt="Cover image">\n'
            '  <h1 class="cover-title">Twitter Archive Book</h1>\n'
            '</div>\n',
            encoding="utf-8",
        )

    if not TITLE_FRAGMENT.exists():
        TITLE_FRAGMENT.write_text(
            '<div class="titlepage">\n'
            '  <h1>Twitter Archive Book</h1>\n'
            '  <p class="byline">Venkatesh Rao</p>\n'
            '</div>\n',
            encoding="utf-8",
        )

    if not PREFACE_FRAGMENT.exists():
        PREFACE_FRAGMENT.write_text(
            '<div class="preface">\n'
            '  <h1>Preface</h1>\n'
            '  <p>Lorem ipsum dolor sit amet. Replace this preface fragment in <code>data/frontmatter/preface.html</code>.</p>\n'
            '</div>\n',
            encoding="utf-8",
        )

    print(f"Frontmatter fragments read from: {FRONT_DIR}")
    print("Frontmatter fragment files: cover.html, title.html, preface.html")


def load_selection(path: Path) -> Tuple[List[str], List[str]]:
    data = json.loads(path.read_text(encoding="utf-8"))

    # Your selection format has evolved. Support common cases.
    if isinstance(data, dict):
        if isinstance(data.get("chapter_threads"), list):
            chapter_threads = [str(x) for x in data["chapter_threads"]]
            comp = data.get("compendium_tweets") or []
            return chapter_threads, [str(x) for x in comp]
        if isinstance(data.get("threads"), list):
            chapter_threads = [str(x) for x in data["threads"]]
            comp = data.get("compendium_tweets") or []
            return chapter_threads, [str(x) for x in comp]

    if isinstance(data, list):
        # assume list of thread ids
        return [str(x) for x in data], []

    raise SystemExit(f"Unrecognized selection format in {path}")


def load_threads(path: Path) -> Dict[str, Dict[str, Any]]:
    threads = {}
    for obj in iter_jsonl(path):
        tid = str(obj.get("thread_id") or obj.get("id") or obj.get("threadId") or "")
        if not tid:
            continue
        threads[tid] = obj
    return threads


def load_tweets_raw(path: Path) -> Dict[str, Dict[str, Any]]:
    tweets = {}
    for obj in iter_jsonl(path):
        rid = str(obj.get("id_str") or obj.get("id") or "")
        if not rid:
            continue
        tweets[rid] = obj
    return tweets


def load_chapter_title_overrides(path: Path) -> Dict[str, str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    chapters = data.get("chapters") if isinstance(data, dict) else None
    if not isinstance(chapters, list):
        raise SystemExit(f"Unexpected chapter_titles format in {path} (expected {{chapters:[...]}})")

    overrides: Dict[str, str] = {}
    for c in chapters:
        tid = c.get("thread_id")
        if not tid:
            continue
        title = (c.get("override_title") or "").strip()
        if not title:
            # Requirement: now use override titles in all cases (you said you filled all)
            raise SystemExit(f"Missing override_title for thread_id {tid} in {path}")
        overrides[str(tid)] = title
    return overrides


def nav_bar(prev_page: Optional[Page], next_page: Optional[Page], base_prefix: str) -> str:
    def label(p: Page) -> str:
        t = escape(p.title)
        if p.chapter_no is not None:
            t = f"{p.chapter_no}. {t}"
        return t

    if prev_page:
        left = f'<a class="nav-link nav-prev" href="{base_prefix}{escape(prev_page.href)}">⬅️ {label(prev_page)}</a>'
    else:
        left = '<span class="nav-link nav-prev disabled">⬅️</span>'

    center = f'<a class="nav-link nav-toc" href="{base_prefix}toc.html">⬆️ ToC</a>'

    if next_page:
        right = f'<a class="nav-link nav-next" href="{base_prefix}{escape(next_page.href)}">{label(next_page)} ➡️</a>'
    else:
        right = '<span class="nav-link nav-next disabled">➡️</span>'

    return (
        '<nav class="book-nav">'
        f'<div class="nav-left">{left}</div>'
        f'<div class="nav-center">{center}</div>'
        f'<div class="nav-right">{right}</div>'
        '</nav>'
    )


def page_shell(title: str, body_html: str, css_href: str, nav_top: str = "", nav_bottom: str = "", subtitle: str = "") -> str:
    subtitle_html = f'<div class="chapter-subtitle">{escape(subtitle)}</div>' if subtitle else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{escape(title)}</title>
  <link rel="stylesheet" href="{escape(css_href)}">
</head>
<body>
  <div class="page">
    {nav_top}
    <div class="page-content">
      <div class="chapter">
        <h1 class="chapter-title">{escape(title)}</h1>
        {subtitle_html}
        {body_html}
      </div>
    </div>
    {nav_bottom}
  </div>
</body>
</html>
"""


def page_shell_no_h1(title: str, body_html: str, css_href: str, nav_top: str = "", nav_bottom: str = "") -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{escape(title)}</title>
  <link rel="stylesheet" href="{escape(css_href)}">
</head>
<body>
  <div class="page">
    {nav_top}
    <div class="page-content">
      <div class="chapter">
        {body_html}
      </div>
    </div>
    {nav_bottom}
  </div>
</body>
</html>
"""


def build_pages(chapter_threads: List[str],
                threads_by_id: Dict[str, Dict[str, Any]],
                tweets_by_id: Dict[str, Dict[str, Any]],
                title_overrides: Dict[str, str]) -> List[Page]:

    cover = Page(href="index.html", title="Cover", kind="cover")
    titlep = Page(href="chapters/title.html", title=TITLEPAGE_TITLE, kind="title")
    toc = Page(href="toc.html", title="Table of Contents", kind="toc")
    preface = Page(href="chapters/preface.html", title=PREFACE_TITLE, kind="preface")
    singletons = Page(href="chapters/compendium.html", title=SINGLETONS_TITLE, kind="singletons", chapter_no=1)

    pages: List[Page] = [cover, titlep, toc, preface, singletons]

    sortable: List[Tuple[datetime, Page]] = []
    for tid in chapter_threads:
        thread = threads_by_id.get(str(tid))
        if not thread or not thread.get("tweets"):
            continue
        root = thread["tweets"][0]
        rid = str(root.get("id_str") or "")
        raw = (tweets_by_id.get(rid) or {}).get("raw") or root.get("raw") or {}
        dt = parse_created_at(root.get("created_at") or raw.get("created_at") or "") or datetime(3000, 1, 1, tzinfo=timezone.utc)

        title = title_overrides[str(tid)]
        p = Page(href=f"chapters/chapter_{tid}.html", title=title, kind="thread")
        p.subtitle = format_long_date(dt)
        sortable.append((dt, p))

    sortable.sort(key=lambda x: x[0])

    ch_no = 2
    for _, p in sortable:
        p.chapter_no = ch_no
        pages.append(p)
        ch_no += 1

    return pages


def write_cover(pages: List[Page]):
    idx = next((i for i, p in enumerate(pages) if p.kind == "cover"), None)
    prevp = pages[idx - 1] if idx is not None and idx > 0 else None
    nextp = pages[idx + 1] if idx is not None and idx + 1 < len(pages) else None
    nav = nav_bar(prevp, nextp, base_prefix="")

    body = COVER_FRAGMENT.read_text(encoding="utf-8")
    html = page_shell_no_h1("Cover", body_html=body, css_href=STYLE_HREF_ROOT, nav_top=nav, nav_bottom=nav)
    COVER_OUT.write_text(html, encoding="utf-8")


def write_title_page(pages: List[Page]):
    idx = next((i for i, p in enumerate(pages) if p.kind == "title"), None)
    prevp = pages[idx - 1] if idx is not None and idx > 0 else None
    nextp = pages[idx + 1] if idx is not None and idx + 1 < len(pages) else None
    nav = nav_bar(prevp, nextp, base_prefix="../")

    body = TITLE_FRAGMENT.read_text(encoding="utf-8")
    html = page_shell_no_h1(TITLEPAGE_TITLE, body_html=body, css_href=STYLE_HREF_CHAPTER, nav_top=nav, nav_bottom=nav)
    TITLE_OUT.write_text(html, encoding="utf-8")


def write_preface_page(pages: List[Page]):
    idx = next((i for i, p in enumerate(pages) if p.kind == "preface"), None)
    prevp = pages[idx - 1] if idx is not None and idx > 0 else None
    nextp = pages[idx + 1] if idx is not None and idx + 1 < len(pages) else None
    nav = nav_bar(prevp, nextp, base_prefix="../")

    body = PREFACE_FRAGMENT.read_text(encoding="utf-8")
    html = page_shell_no_h1(PREFACE_TITLE, body_html=body, css_href=STYLE_HREF_CHAPTER, nav_top=nav, nav_bottom=nav)
    PREFACE_OUT.write_text(html, encoding="utf-8")


def write_toc(pages: List[Page]):
    items: List[str] = []
    # self link first
    items.append('<li class="toc-self"><a href="toc.html">Table of Contents</a></li>')

    for p in pages:
        if p.kind == "toc":
            continue
        label = escape(p.title)
        if p.chapter_no is not None:
            label = f"{p.chapter_no}. {label}"
        items.append(f'<li class="toc-item toc-{escape(p.kind)}"><a href="{escape(p.href)}">{label}</a></li>')

    body = '<h1>Table of Contents</h1>' + f'<ul class="chapter-list">{"".join(items)}</ul>'

    idx = next((i for i, p in enumerate(pages) if p.kind == "toc"), None)
    prevp = pages[idx - 1] if idx is not None and idx > 0 else None
    nextp = pages[idx + 1] if idx is not None and idx + 1 < len(pages) else None
    nav = nav_bar(prevp, nextp, base_prefix="")

    html = page_shell_no_h1("Table of Contents", body_html=body, css_href=STYLE_HREF_ROOT, nav_top=nav, nav_bottom=nav)
    TOC_OUT.write_text(html, encoding="utf-8")


def clear_old_thread_chapters():
    if not CHAPTERS_DIR.exists():
        return
    removed = 0
    for p in CHAPTERS_DIR.glob("chapter_*.html"):
        p.unlink()
        removed += 1
    print(f"Cleared old thread chapter HTML files: {removed}")


def render_quote_boxes(tweet: Dict[str, Any], tweets_by_id: Dict[str, Dict[str, Any]]) -> str:
    # Keep existing logic minimal: if tweet has quoted_id, render it as a stylable block.
    qid = tweet.get("quoted_id")
    if not qid:
        return ""
    qt = tweets_by_id.get(str(qid), {}).get("raw") or {}
    qtext = qt.get("full_text") or qt.get("text") or ""
    if not qtext:
        return ""
    # Note: quote text cleanup handled via tweet_text_cleanup when rendering main text; here we keep it simple.
    qsafe = escape(qtext).replace("\n", "<br>\n")
    return f'<blockquote class="quote-box"><div class="quote-text">{qsafe}</div></blockquote>'


def render_media(tweet_raw: Dict[str, Any]) -> str:
    ee = tweet_raw.get("extended_entities") or {}
    media = ee.get("media") or (tweet_raw.get("entities") or {}).get("media") or []
    if not media:
        return ""

    bits: List[str] = ['<div class="tweet-media">']
    for m in media:
        t = (m.get("type") or "").lower()
        url = m.get("media_url_https") or m.get("media_url") or ""
        basename = (Path(url).name if url else "").split("?")[0]
        if not basename:
            continue
        local = f"../assets/media/{escape(basename)}"
        if t == "photo":
            bits.append(f'<img class="tweet-photo" src="{local}" alt="tweet image">')
        elif t in ("video", "animated_gif"):
            variants = (((m.get("video_info") or {}).get("variants")) or [])
            mp4 = None
            for v in variants:
                if (v.get("content_type") or "") == "video/mp4":
                    mp4 = v.get("url")
                    break
            # We rely on local mp4 basename already copied into assets/media with same basename as URL when possible.
            bits.append(f'<video class="tweet-video" src="{local}" controls preload="metadata"></video>')
        else:
            bits.append(f'<a href="{local}">media</a>')
    bits.append("</div>")
    return "\n".join(bits)


def generate_thread_chapter_html(page: Page,
                                thread: Dict[str, Any],
                                tweets_by_id: Dict[str, Dict[str, Any]]) -> str:
    from tweet_text_cleanup import render_tweet_text_html  # local module in data/

    tweets = thread.get("tweets") or []
    parts: List[str] = []

    for tw in tweets:
        rid = str(tw.get("id_str") or "")
        raw = (tweets_by_id.get(rid) or {}).get("raw") or tw.get("raw") or {}
        text = raw.get("full_text") or raw.get("text") or tw.get("text") or ""
        text_html = render_tweet_text_html(text, raw, link_label="link")

        # tweet card
        parts.append('<div class="tweet">')
        parts.append(f'  <div class="tweet-text">{text_html}</div>')

        # Quote boxes (stylable)
        # (Your existing pipeline also embeds self-quotes; this is additive/minimal.)
        parts.append(render_quote_boxes({"quoted_id": tw.get("quoted_id")}, tweets_by_id))

        # Media (stylable width in CSS)
        parts.append(render_media(raw))

        parts.append("</div>")

    body = "\n".join(parts)
    # Navigation base is "../" because chapters live under book/chapters/
    return page_shell(
        title=(f"{page.chapter_no}. {page.title}" if page.chapter_no else page.title),
        subtitle=page.subtitle,
        body_html=body,
        css_href=STYLE_HREF_CHAPTER,
    )


def patch_nav_in_html(html: str, nav_top: str, nav_bottom: str) -> str:
    # If the page already contains <nav class="book-nav"> ... </nav>, replace the first and last occurrences.
    nav_re = re.compile(r"<nav class=\"book-nav\">[\s\S]*?</nav>")
    matches = list(nav_re.finditer(html))
    if len(matches) >= 2:
        html = nav_re.sub(lambda m, c=[0]: (nav_top if (c.__setitem__(0, c[0]+1) or c[0]) == 1 else nav_bottom if c[0] == len(matches) else m.group(0)), html)
    elif len(matches) == 1:
        html = nav_re.sub(nav_top, html, count=1)
    return html


def write_thread_chapters(pages: List[Page], threads_by_id: Dict[str, Dict[str, Any]], tweets_by_id: Dict[str, Dict[str, Any]]):
    # Build lookup for prev/next nav
    by_href = {p.href: p for p in pages}

    for i, p in enumerate(pages):
        if p.kind != "thread":
            continue
        thread_id = p.href.replace("chapters/chapter_", "").replace(".html", "")
        thread = threads_by_id.get(thread_id)
        if not thread:
            continue

        prevp = pages[i - 1] if i > 0 else None
        nextp = pages[i + 1] if i + 1 < len(pages) else None
        nav = nav_bar(prevp, nextp, base_prefix="../")

        html = generate_thread_chapter_html(p, thread, tweets_by_id)
        # inject nav
        html = html.replace('<div class="page">', f'<div class="page">\n    {nav}', 1)
        html = html.replace('</div>\n</body>', f'    {nav}\n  </div>\n</body>', 1)

        out_path = BOOK_DIR / p.href
        out_path.write_text(html, encoding="utf-8")


def patch_compendium_nav(pages: List[Page]):
    comp = CHAPTERS_DIR / "compendium.html"
    if not comp.exists():
        # Create a minimal stub so the ToC link isn't dead.
        stub = page_shell_no_h1(
            title=SINGLETONS_TITLE,
            body_html='<h1>Noteworthy Singletons</h1><p>Compendium page not generated yet.</p>',
            css_href=STYLE_HREF_CHAPTER,
        )
        comp.write_text(stub, encoding="utf-8")
        return

    idx = next((i for i, p in enumerate(pages) if p.kind == "singletons"), None)
    if idx is None:
        return
    prevp = pages[idx - 1] if idx > 0 else None
    nextp = pages[idx + 1] if idx + 1 < len(pages) else None
    nav = nav_bar(prevp, nextp, base_prefix="../")

    html = comp.read_text(encoding="utf-8")
    # If compendium was generated with its own nav, replace it; else inject at top/bottom.
    if '<nav class="book-nav">' in html:
        html = patch_nav_in_html(html, nav, nav)
    else:
        html = html.replace('<div class="page">', f'<div class="page">\n    {nav}', 1)
        html = html.replace('</div>\n</body>', f'    {nav}\n  </div>\n</body>', 1)
    comp.write_text(html, encoding="utf-8")


def maybe_run_cleanup(run_cleanup: bool):
    if not run_cleanup:
        print("Tweet text cleanup: skipped (use --run-cleanup to invoke).")
        return

    script = DATA_DIR / "tweet_text_cleanup.py"
    if not script.exists():
        raise SystemExit(f"Expected cleanup script not found: {script}")

    print(f"Tweet text cleanup: running {script} ...")
    subprocess.run(["python3", str(script)], check=True)


def ensure_dirs():
    BOOK_DIR.mkdir(parents=True, exist_ok=True)
    CHAPTERS_DIR.mkdir(parents=True, exist_ok=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-cleanup", action="store_true", help="Invoke data/tweet_text_cleanup.py before generating.")
    args = ap.parse_args()

    ensure_dirs()
    ensure_frontmatter_fragments()

    maybe_run_cleanup(args.run_cleanup)

    print(f"Loading selection from {SELECTION_JSON} ...")
    chapter_threads, _ = load_selection(SELECTION_JSON)
    print(f"Selected chapter threads: {len(chapter_threads)}")

    print(f"Loading threads from {THREADS_JSONL} ...")
    threads_by_id = load_threads(THREADS_JSONL)

    print(f"Loading tweets (with raw) from {TWEETS_JSONL} ...")
    tweets_by_id = load_tweets_raw(TWEETS_JSONL)

    print(f"Loading title overrides from {CHAPTER_TITLES_JSON} ...")
    title_overrides = load_chapter_title_overrides(CHAPTER_TITLES_JSON)

    pages = build_pages(chapter_threads, threads_by_id, tweets_by_id, title_overrides)

    # Generate outputs
    clear_old_thread_chapters()
    write_cover(pages)
    write_title_page(pages)
    write_toc(pages)
    write_preface_page(pages)
    patch_compendium_nav(pages)
    write_thread_chapters(pages, threads_by_id, tweets_by_id)

    print(f"Wrote cover: {COVER_OUT}")
    print(f"Wrote ToC: {TOC_OUT}")
    print(f"Wrote title: {TITLE_OUT}")
    print(f"Wrote preface: {PREFACE_OUT}")
    print(f"Patched/checked singletons: {CHAPTERS_DIR / 'compendium.html'}")


if __name__ == "__main__":
    main()
