#!/usr/bin/env python3
"""
Generate static HTML "book" from selected Twitter threads, using chapter_titles.json overrides.

Key behaviors:
- Cover is book/index.html (content pulled from data/frontmatter/cover.html)
- Title page is book/chapters/title.html (from data/frontmatter/title.html)
- ToC is book/toc.html (generated), placed after title and before preface in reading order
- Preface is book/chapters/preface.html (from data/frontmatter/preface.html)
- "Noteworthy Singletons" is book/chapters/compendium.html (generated by separate compendium script)
- Thread chapters are generated as book/chapters/chapter_<thread_id>.html

Constraints:
- Does NOT overwrite book/style.css (so your manual CSS edits persist).
- Frontmatter fragment files are created ONLY if missing; rendered pages are updated every run.
- Thread chapters are always regenerated; frontmatter pages are regenerated; compendium is left intact
  but this script will patch its navigation bar if it finds it.

Optional:
- --run-cleanup invokes data/tweet_text_cleanup.py as a standalone script (if you want).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from html import escape, unescape
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

DATA_DIR = ROOT / "data"
BOOK_DIR = ROOT / "book"
CHAPTERS_DIR = BOOK_DIR / "chapters"

THREADS_JSONL = DATA_DIR / "threads_data_ops_patched.jsonl"
TWEETS_JSONL = DATA_DIR / "tweets_normalized.jsonl"
SELECTION_JSON = DATA_DIR / "selection_final_clean.json"
CHAPTER_TITLES_JSON = DATA_DIR / "chapter_titles.json"

FRONT_DIR = DATA_DIR / "frontmatter"
COVER_FRAGMENT = FRONT_DIR / "cover.html"
TITLE_FRAGMENT = FRONT_DIR / "title.html"
PREFACE_FRAGMENT = FRONT_DIR / "preface.html"

STYLE_HREF_ROOT = "style.css"
STYLE_HREF_CHAPTER = "../style.css"

# Output paths
COVER_OUT = BOOK_DIR / "index.html"
TOC_OUT = BOOK_DIR / "toc.html"
TITLE_OUT = CHAPTERS_DIR / "title.html"
PREFACE_OUT = CHAPTERS_DIR / "preface.html"

SINGLETONS_TITLE = "Singles"
TITLEPAGE_TITLE = "Title page"
PREFACE_TITLE = "Preface"
BOOK_TITLE = "vgr: The Twitter Years (2007\u201322)"
BOOK_DESCRIPTION = "A curated collection of tweets and threads by Venkatesh Rao (@vgr), 2007\u201322."
SITE_BASE_URL = "https://venkateshrao.com/twitter-book"
COVER_IMAGE_URL = SITE_BASE_URL + "/assets/cover.png"


@dataclass
class Page:
    href: str
    title: str
    kind: str               # cover | title | toc | preface | singletons | thread
    chapter_no: Optional[int] = None
    subtitle: str = ""      # used for thread date subtitle


def iter_jsonl(path: Path):
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            yield json.loads(line)


def parse_created_at(s: str) -> Optional[datetime]:
    # Twitter created_at format: "Wed Oct 10 20:19:24 +0000 2018"
    if not s:
        return None
    try:
        # try strict twitter format
        return datetime.strptime(s, "%a %b %d %H:%M:%S %z %Y")
    except Exception:
        pass
    # fallback: ISO-ish
    try:
        dt = datetime.fromisoformat(s.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    except Exception:
        return None


def format_long_date(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).strftime("%B %-d, %Y") if os.name != "nt" else dt.astimezone(timezone.utc).strftime("%B %#d, %Y")


def ensure_frontmatter_fragments():
    FRONT_DIR.mkdir(parents=True, exist_ok=True)

    if not COVER_FRAGMENT.exists():
        COVER_FRAGMENT.write_text(
            '<div class="cover">\n'
            '  <img class="cover-image" src="assets/cover.png" alt="Cover image">\n'
            '  <h1 class="cover-title">Twitter Archive Book</h1>\n'
            '</div>\n',
            encoding="utf-8",
        )

    if not TITLE_FRAGMENT.exists():
        TITLE_FRAGMENT.write_text(
            '<div class="titlepage">\n'
            '  <h1>Twitter Archive Book</h1>\n'
            '  <p class="byline">Venkatesh Rao</p>\n'
            '</div>\n',
            encoding="utf-8",
        )

    if not PREFACE_FRAGMENT.exists():
        PREFACE_FRAGMENT.write_text(
            '<div class="preface">\n'
            '  <h1>Preface</h1>\n'
            '  <p>Lorem ipsum dolor sit amet. Replace this preface fragment in <code>data/frontmatter/preface.html</code>.</p>\n'
            '</div>\n',
            encoding="utf-8",
        )

    print(f"Frontmatter fragments read from: {FRONT_DIR}")
    print("Frontmatter fragment files: cover.html, title.html, preface.html")


def load_selection(path: Path) -> Tuple[List[str], List[str]]:
    data = json.loads(path.read_text(encoding="utf-8"))

    # Your selection format has evolved. Support common cases.
    if isinstance(data, dict):
        if isinstance(data.get("chapter_threads"), list):
            chapter_threads = [str(x) for x in data["chapter_threads"]]
            comp = data.get("compendium_tweets") or []
            return chapter_threads, [str(x) for x in comp]
        if isinstance(data.get("threads"), list):
            chapter_threads = [str(x) for x in data["threads"]]
            comp = data.get("compendium_tweets") or []
            return chapter_threads, [str(x) for x in comp]

    if isinstance(data, list):
        # assume list of thread ids
        return [str(x) for x in data], []

    raise SystemExit(f"Unrecognized selection format in {path}")


def load_threads(path: Path) -> Dict[str, Dict[str, Any]]:
    threads = {}
    for obj in iter_jsonl(path):
        tid = str(obj.get("thread_id") or obj.get("id") or obj.get("threadId") or "")
        if not tid:
            continue
        threads[tid] = obj
    return threads


def load_tweets_raw(path: Path) -> Dict[str, Dict[str, Any]]:
    tweets = {}
    for obj in iter_jsonl(path):
        rid = str(obj.get("id_str") or obj.get("id") or "")
        if not rid:
            continue
        tweets[rid] = obj
    return tweets


def load_chapter_title_overrides(path: Path) -> Dict[str, str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    chapters = data.get("chapters") if isinstance(data, dict) else None
    if not isinstance(chapters, list):
        raise SystemExit(f"Unexpected chapter_titles format in {path} (expected {{chapters:[...]}})")

    overrides: Dict[str, str] = {}
    for c in chapters:
        tid = c.get("thread_id")
        if not tid:
            continue
        title = (c.get("override_title") or "").strip()
        if not title:
            # Requirement: now use override titles in all cases (you said you filled all)
            raise SystemExit(f"Missing override_title for thread_id {tid} in {path}")
        overrides[str(tid)] = title
    return overrides


def nav_bar(prev_page: Optional[Page], next_page: Optional[Page], base_prefix: str) -> str:
    def label(p: Page) -> str:
        t = escape(p.title)
        if p.chapter_no is not None:
            t = f"{p.chapter_no}. {t}"
        return t

    if prev_page:
        left = f'<a class="nav-link nav-prev" href="{base_prefix}{escape(prev_page.href)}"><span class="nav-arrow">&larr;</span><span class="nav-label">{label(prev_page)}</span></a>'
    else:
        left = '<span class="nav-link nav-prev disabled"><span class="nav-arrow">&larr;</span></span>'

    center = f'<a class="nav-link nav-toc" href="{base_prefix}toc.html">Table of Contents</a>'

    if next_page:
        right = f'<a class="nav-link nav-next" href="{base_prefix}{escape(next_page.href)}"><span class="nav-label">{label(next_page)}</span><span class="nav-arrow">&rarr;</span></a>'
    else:
        right = '<span class="nav-link nav-next disabled"><span class="nav-arrow">&rarr;</span></span>'

    return (
        '<nav class="book-nav">'
        f'<div class="nav-left">{left}</div>'
        f'<div class="nav-center">{center}</div>'
        f'<div class="nav-right">{right}</div>'
        '</nav>'
    )


def floating_nav(prev_page: Optional[Page], next_page: Optional[Page], base_prefix: str) -> str:
    toc_href = f"{base_prefix}toc.html"
    parts = []
    if prev_page:
        parts.append(
            f'<a class="float-nav float-nav-prev" href="{base_prefix}{escape(prev_page.href)}" title="Previous chapter">'
            f'<span class="float-nav-chevron">&lsaquo;</span>'
            f'<span class="float-nav-label">Ch. &minus;</span>'
            f'</a>'
        )
    right_parts = []
    right_parts.append(
        f'<a class="float-nav-btn float-nav-toc" href="{escape(toc_href)}" title="Table of Contents">'
        f'<span class="float-nav-chevron">&and;</span>'
        f'<span class="float-nav-label">ToC</span>'
        f'</a>'
    )
    if next_page:
        right_parts.append(
            f'<a class="float-nav-btn float-nav-next" href="{base_prefix}{escape(next_page.href)}" title="Next chapter">'
            f'<span class="float-nav-chevron">&rsaquo;</span>'
            f'<span class="float-nav-label">Ch. +</span>'
            f'</a>'
        )
    parts.append(f'<div class="float-nav-right">{"".join(right_parts)}</div>')
    return "\n".join(parts)


def social_meta(doc_title: str, description: str = BOOK_DESCRIPTION) -> str:
    return (
        f'  <meta property="og:title" content="{escape(doc_title)}">\n'
        f'  <meta property="og:description" content="{escape(description)}">\n'
        f'  <meta property="og:image" content="{escape(COVER_IMAGE_URL)}">\n'
        f'  <meta property="og:type" content="book">\n'
        f'  <meta name="twitter:card" content="summary_large_image">\n'
        f'  <meta name="twitter:title" content="{escape(doc_title)}">\n'
        f'  <meta name="twitter:description" content="{escape(description)}">\n'
        f'  <meta name="twitter:image" content="{escape(COVER_IMAGE_URL)}">'
    )


def page_shell(title: str, body_html: str, css_href: str, nav_top: str = "", nav_bottom: str = "", subtitle: str = "", summary: str = "", meta_title: str = "", float_nav: str = "") -> str:
    subtitle_html = f'<div class="chapter-subtitle">{escape(subtitle)}</div>' if subtitle else ""
    summary_html = f'<div class="chapter-summary"><em>{escape(summary)}</em></div>' if summary else ""
    doc_title = meta_title if meta_title else title
    og_desc = summary if summary else BOOK_DESCRIPTION
    css_dir = css_href.rsplit("style.css", 1)[0]
    mobile_href = css_dir + "mobile.css"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(doc_title)}</title>
{social_meta(doc_title, og_desc)}
  <link rel="stylesheet" href="{escape(css_href)}">
  <link rel="stylesheet" href="{escape(mobile_href)}">
</head>
<body>
  <div class="page">
    {nav_top}
    <div class="page-content">
      <div class="chapter">
        <h1 class="chapter-title">{escape(title)} <a class="chapter-permalink" href="#" title="Copy link to this page" onclick="return copyPageLink(this)">&#x1F517;</a></h1>
        {subtitle_html}
        {summary_html}
        {body_html}
      </div>
    </div>
    {nav_bottom}
  </div>
  {float_nav}
<script>
function copyPageLink(el) {{
  navigator.clipboard.writeText(window.location.origin + window.location.pathname).then(function() {{
    var tip = document.createElement('span');
    tip.className = 'copy-tooltip';
    tip.textContent = 'Link copied!';
    el.appendChild(tip);
    setTimeout(function() {{ tip.remove(); }}, 1800);
  }});
  return false;
}}
function copyTweetLink(el, id) {{
  var tweet = document.getElementById(id);
  if (!tweet) return false;
  var url = window.location.origin + window.location.pathname + '#' + id;
  navigator.clipboard.writeText(url).then(function() {{
    var tip = document.createElement('span');
    tip.className = 'copy-tooltip';
    tip.textContent = 'Link copied!';
    el.appendChild(tip);
    setTimeout(function() {{ tip.remove(); }}, 1800);
  }});
  var y = tweet.getBoundingClientRect().top + window.pageYOffset - 100;
  window.scrollTo({{ top: y, behavior: 'smooth' }});
  var prev = document.querySelector('.permalink-highlight');
  if (prev) prev.classList.remove('permalink-highlight');
  tweet.classList.add('permalink-highlight');
  history.replaceState(null, '', '#' + id);
  return false;
}}
(function() {{
  if (window.location.hash) {{
    var id = window.location.hash.substring(1);
    var tweet = document.getElementById(id);
    if (tweet) {{
      setTimeout(function() {{
        var y = tweet.getBoundingClientRect().top + window.pageYOffset - 100;
        window.scrollTo({{ top: y, behavior: 'smooth' }});
        tweet.classList.add('permalink-highlight');
      }}, 300);
    }}
  }}
}})();
</script>
</body>
</html>
"""


def page_shell_no_h1(title: str, body_html: str, css_href: str, nav_top: str = "", nav_bottom: str = "", meta_title: str = "", float_nav: str = "") -> str:
    doc_title = meta_title if meta_title else title
    css_dir = css_href.rsplit("style.css", 1)[0]
    mobile_href = css_dir + "mobile.css"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(doc_title)}</title>
{social_meta(doc_title)}
  <link rel="stylesheet" href="{escape(css_href)}">
  <link rel="stylesheet" href="{escape(mobile_href)}">
</head>
<body>
  <div class="page">
    {nav_top}
    <div class="page-content">
      <div class="chapter">
        {body_html}
      </div>
    </div>
    {nav_bottom}
  </div>
  {float_nav}
</body>
</html>
"""


def build_pages(chapter_threads: List[str],
                threads_by_id: Dict[str, Dict[str, Any]],
                tweets_by_id: Dict[str, Dict[str, Any]],
                title_overrides: Dict[str, str]) -> List[Page]:

    cover = Page(href="index.html", title="Cover", kind="cover")
    titlep = Page(href="chapters/title.html", title=TITLEPAGE_TITLE, kind="title")
    toc = Page(href="toc.html", title="Table of Contents", kind="toc")
    preface = Page(href="chapters/preface.html", title=PREFACE_TITLE, kind="preface")
    singletons = Page(href="chapters/compendium.html", title=SINGLETONS_TITLE, kind="singletons", chapter_no=1)

    pages: List[Page] = [cover, titlep, toc, preface, singletons]

    sortable: List[Tuple[datetime, Page]] = []
    for tid in chapter_threads:
        thread = threads_by_id.get(str(tid))
        if not thread or not thread.get("tweets"):
            continue
        root = thread["tweets"][0]
        rid = str(root.get("id_str") or "")
        raw = (tweets_by_id.get(rid) or {}).get("raw") or root.get("raw") or {}
        dt = parse_created_at(root.get("created_at") or raw.get("created_at") or "") or datetime(3000, 1, 1, tzinfo=timezone.utc)

        title = title_overrides[str(tid)]
        p = Page(href=f"chapters/chapter_{tid}.html", title=title, kind="thread")
        p.subtitle = format_long_date(dt)
        sortable.append((dt, p))

    sortable.sort(key=lambda x: x[0])

    ch_no = 2
    for _, p in sortable:
        p.chapter_no = ch_no
        pages.append(p)
        ch_no += 1

    return pages


def write_cover(pages: List[Page]):
    idx = next((i for i, p in enumerate(pages) if p.kind == "cover"), None)
    prevp = pages[idx - 1] if idx is not None and idx > 0 else None
    nextp = pages[idx + 1] if idx is not None and idx + 1 < len(pages) else None
    nav = nav_bar(prevp, nextp, base_prefix="")
    fnav = floating_nav(prevp, nextp, base_prefix="")

    body = COVER_FRAGMENT.read_text(encoding="utf-8")
    html = page_shell_no_h1("Cover", body_html=body, css_href=STYLE_HREF_ROOT, nav_top=nav, nav_bottom=nav, meta_title=BOOK_TITLE, float_nav=fnav)
    COVER_OUT.write_text(html, encoding="utf-8")


def write_title_page(pages: List[Page]):
    idx = next((i for i, p in enumerate(pages) if p.kind == "title"), None)
    prevp = pages[idx - 1] if idx is not None and idx > 0 else None
    nextp = pages[idx + 1] if idx is not None and idx + 1 < len(pages) else None
    nav = nav_bar(prevp, nextp, base_prefix="../")
    fnav = floating_nav(prevp, nextp, base_prefix="../")

    body = TITLE_FRAGMENT.read_text(encoding="utf-8")
    html = page_shell_no_h1(TITLEPAGE_TITLE, body_html=body, css_href=STYLE_HREF_CHAPTER, nav_top=nav, nav_bottom=nav, meta_title=BOOK_TITLE, float_nav=fnav)
    TITLE_OUT.write_text(html, encoding="utf-8")


def write_preface_page(pages: List[Page]):
    idx = next((i for i, p in enumerate(pages) if p.kind == "preface"), None)
    prevp = pages[idx - 1] if idx is not None and idx > 0 else None
    nextp = pages[idx + 1] if idx is not None and idx + 1 < len(pages) else None
    nav = nav_bar(prevp, nextp, base_prefix="../")
    fnav = floating_nav(prevp, nextp, base_prefix="../")

    body = PREFACE_FRAGMENT.read_text(encoding="utf-8")
    meta = f"{BOOK_TITLE} | Preface"
    html = page_shell_no_h1(PREFACE_TITLE, body_html=body, css_href=STYLE_HREF_CHAPTER, nav_top=nav, nav_bottom=nav, meta_title=meta, float_nav=fnav)
    PREFACE_OUT.write_text(html, encoding="utf-8")


def write_toc(pages: List[Page]):
    summaries = load_chapter_summaries()
    items: List[str] = []

    skip_kinds = {"toc", "cover", "title"}
    for p in pages:
        if p.kind in skip_kinds:
            continue
        label = escape(p.title)
        if p.chapter_no is not None:
            label = f"{p.chapter_no}. {label}"

        # Add date in parentheses for threads
        date_span = ""
        if p.subtitle:
            date_span = f' <span class="toc-date">({escape(p.subtitle)})</span>'

        # Add hover tooltip for chapters with summaries
        thread_id = p.href.replace("chapters/chapter_", "").replace(".html", "")
        summary = summaries.get(thread_id, "")
        tooltip = ""
        if summary:
            tooltip = f'<span class="toc-tooltip">{escape(summary)}</span>'

        li_class = f'toc-item toc-{escape(p.kind)}'
        if summary:
            li_class += " has-tooltip"
        items.append(
            f'<li class="{li_class}">'
            f'<a href="{escape(p.href)}">{label}{date_span}</a>'
            f'{tooltip}</li>'
        )

    body = '<h1>Table of Contents</h1>' + f'<ul class="toc-list">{"".join(items)}</ul>'

    idx = next((i for i, p in enumerate(pages) if p.kind == "toc"), None)
    prevp = pages[idx - 1] if idx is not None and idx > 0 else None
    nextp = pages[idx + 1] if idx is not None and idx + 1 < len(pages) else None
    nav = nav_bar(prevp, nextp, base_prefix="")
    fnav = floating_nav(prevp, nextp, base_prefix="")

    toc_meta = f"{BOOK_TITLE} | Table of Contents"
    html = page_shell_no_h1("Table of Contents", body_html=body, css_href=STYLE_HREF_ROOT, nav_top=nav, nav_bottom=nav, meta_title=toc_meta, float_nav=fnav)
    TOC_OUT.write_text(html, encoding="utf-8")


def clear_old_thread_chapters():
    if not CHAPTERS_DIR.exists():
        return
    removed = 0
    for p in CHAPTERS_DIR.glob("chapter_*.html"):
        p.unlink()
        removed += 1
    print(f"Cleared old thread chapter HTML files: {removed}")


def _render_single_quote_box(tweet_id: str, tweets_by_id: Dict[str, Dict[str, Any]]) -> str:
    """Render a single tweet as a quote box, if it exists in the archive."""
    qt = tweets_by_id.get(str(tweet_id), {})
    raw = qt.get("raw") or {}
    qtext = raw.get("full_text") or raw.get("text") or ""
    if not qtext:
        return ""
    qsafe = escape(unescape(qtext)).replace("\n", "<br>\n")
    return f'<blockquote class="quote-box"><div class="quote-text">{qsafe}</div></blockquote>'


def render_quote_boxes(tweet: Dict[str, Any], tweets_by_id: Dict[str, Dict[str, Any]]) -> str:
    # If tweet has quoted_id, render it as a stylable block.
    qid = tweet.get("quoted_id")
    if not qid:
        return ""
    return _render_single_quote_box(qid, tweets_by_id)


_SELF_TWEET_RE = re.compile(r'twitter\.com/vgr/status/(\d+)')


def render_self_tweet_quotes(raw: Dict[str, Any], tweets_by_id: Dict[str, Dict[str, Any]],
                             current_tweet_id: str = "") -> str:
    """
    Find self-tweet URLs (twitter.com/vgr/status/...) in entity URLs,
    look up the referenced tweet in the archive, and render as quote boxes.
    Skips the current tweet to avoid self-quoting.
    """
    entities = (raw or {}).get("entities") or {}
    urls = entities.get("urls") or []
    boxes: List[str] = []
    seen: set = set()
    for u in urls:
        expanded = u.get("expanded_url") or ""
        m = _SELF_TWEET_RE.search(expanded)
        if not m:
            continue
        tid = m.group(1)
        if tid == current_tweet_id or tid in seen:
            continue
        seen.add(tid)
        box = _render_single_quote_box(tid, tweets_by_id)
        if box:
            boxes.append(box)
    return "\n".join(boxes)


def render_media(tweet_raw: Dict[str, Any]) -> str:
    ee = tweet_raw.get("extended_entities") or {}
    media = ee.get("media") or (tweet_raw.get("entities") or {}).get("media") or []
    if not media:
        return ""

    bits: List[str] = ['<div class="tweet-media">']
    for m in media:
        t = (m.get("type") or "").lower()
        url = m.get("media_url_https") or m.get("media_url") or ""
        basename = (Path(url).name if url else "").split("?")[0]
        if not basename:
            continue
        local = f"../assets/media/{escape(basename)}"
        if t == "photo":
            bits.append(f'<img class="tweet-photo" src="{local}" alt="tweet image">')
        elif t in ("video", "animated_gif"):
            # Find best mp4 variant URL and derive local basename
            variants = (((m.get("video_info") or {}).get("variants")) or [])
            mp4_variants = [v for v in variants if (v.get("content_type") or "") == "video/mp4"]
            mp4_variants.sort(key=lambda v: v.get("bitrate", 0), reverse=True)
            if mp4_variants:
                mp4_url = mp4_variants[0].get("url", "")
                mp4_basename = mp4_url.split("/")[-1].split("?")[0] if mp4_url else ""
                if mp4_basename:
                    local = f"../assets/media/{escape(mp4_basename)}"
            autoplay = ' autoplay loop muted playsinline' if t == "animated_gif" else ' controls'
            bits.append(f'<video class="tweet-video" src="{local}"{autoplay} preload="metadata"></video>')
        else:
            bits.append(f'<a href="{local}">media</a>')
    bits.append("</div>")
    return "\n".join(bits)


def generate_thread_chapter_html(page: Page,
                                thread: Dict[str, Any],
                                tweets_by_id: Dict[str, Dict[str, Any]],
                                url_titles: Optional[Dict[str, Any]] = None,
                                url_overrides: Optional[Dict[str, Any]] = None,
                                summary: str = "") -> str:
    from tweet_text_cleanup import render_tweet_text_html  # local module in data/

    tweets = thread.get("tweets") or []
    parts: List[str] = []
    endnotes: List[Dict[str, str]] = []

    for tw in tweets:
        rid = str(tw.get("id_str") or "")
        raw = (tweets_by_id.get(rid) or {}).get("raw") or tw.get("raw") or {}
        text = raw.get("full_text") or raw.get("text") or tw.get("text") or ""
        text_html = render_tweet_text_html(text, raw, url_titles=url_titles, url_overrides=url_overrides, embed_self_tweets=True, endnotes=endnotes)

        # tweet card
        parts.append(f'<div class="tweet" id="t{escape(rid)}">')
        parts.append(f'  <a class="tweet-permalink" href="#t{escape(rid)}" title="Copy link to this tweet" onclick="return copyTweetLink(this, \'t{escape(rid)}\')">&#x1F517;</a>')
        parts.append(f'  <div class="tweet-text">{text_html}</div>')

        # Quote boxes: explicit quoted_id
        parts.append(render_quote_boxes({"quoted_id": tw.get("quoted_id")}, tweets_by_id))

        # Self-tweet links rendered as inline quotes
        parts.append(render_self_tweet_quotes(raw, tweets_by_id, current_tweet_id=rid))

        # Media (stylable width in CSS)
        parts.append(render_media(raw))

        parts.append("</div>")

    # Render endnotes section if any external tweet references were collected
    if endnotes:
        parts.append('<div class="chapter-endnotes">')
        parts.append('<h2 class="endnotes-title">Notes</h2>')
        parts.append('<ol class="endnotes-list">')
        for note in endnotes:
            num = note["num"]
            handle = escape(note["handle"])
            url = escape(note["url"])
            parts.append(
                f'<li id="endnote-{num}" class="endnote-item">'
                f'@{handle} &mdash; <a href="{url}" target="_blank" rel="noreferrer">{url}</a>'
                f'</li>'
            )
        parts.append('</ol>')
        parts.append('</div>')

    body = "\n".join(parts)
    chapter_display = f"{page.chapter_no}. {page.title}" if page.chapter_no else page.title
    chapter_meta = f"{BOOK_TITLE} | {chapter_display}"
    # Navigation base is "../" because chapters live under book/chapters/
    return page_shell(
        title=chapter_display,
        subtitle=page.subtitle,
        body_html=body,
        css_href=STYLE_HREF_CHAPTER,
        summary=summary,
        meta_title=chapter_meta,
    )


def patch_nav_in_html(html: str, nav_top: str, nav_bottom: str) -> str:
    # If the page already contains <nav class="book-nav"> ... </nav>, replace the first and last occurrences.
    nav_re = re.compile(r"<nav class=\"book-nav\">[\s\S]*?</nav>")
    matches = list(nav_re.finditer(html))
    if len(matches) >= 2:
        html = nav_re.sub(lambda m, c=[0]: (nav_top if (c.__setitem__(0, c[0]+1) or c[0]) == 1 else nav_bottom if c[0] == len(matches) else m.group(0)), html)
    elif len(matches) == 1:
        html = nav_re.sub(nav_top, html, count=1)
    return html


def load_chapter_summaries() -> Dict[str, str]:
    """Load hand-edited chapter summaries keyed by thread_id."""
    path = DATA_DIR / "chapter_summaries.json"
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("summaries") or {}


def write_thread_chapters(pages: List[Page], threads_by_id: Dict[str, Dict[str, Any]], tweets_by_id: Dict[str, Dict[str, Any]], url_titles: Optional[Dict[str, Any]] = None, url_overrides: Optional[Dict[str, Any]] = None):
    # Build lookup for prev/next nav
    by_href = {p.href: p for p in pages}
    summaries = load_chapter_summaries()

    for i, p in enumerate(pages):
        if p.kind != "thread":
            continue
        thread_id = p.href.replace("chapters/chapter_", "").replace(".html", "")
        thread = threads_by_id.get(thread_id)
        if not thread:
            continue

        prevp = pages[i - 1] if i > 0 else None
        nextp = pages[i + 1] if i + 1 < len(pages) else None
        nav = nav_bar(prevp, nextp, base_prefix="../")
        fnav = floating_nav(prevp, nextp, base_prefix="../")

        summary = summaries.get(thread_id, "")
        html = generate_thread_chapter_html(p, thread, tweets_by_id, url_titles=url_titles, url_overrides=url_overrides, summary=summary)
        # inject top nav
        html = html.replace('<div class="page">', f'<div class="page">\n    {nav}', 1)
        # inject bottom nav + floating nav before </body>
        html = html.replace('</body>', f'{nav}\n{fnav}\n</body>', 1)

        out_path = BOOK_DIR / p.href
        out_path.write_text(html, encoding="utf-8")


def patch_compendium_nav(pages: List[Page]):
    comp = CHAPTERS_DIR / "compendium.html"
    if not comp.exists():
        # Create a minimal stub so the ToC link isn't dead.
        stub = page_shell_no_h1(
            title=SINGLETONS_TITLE,
            body_html='<h1>Singles</h1><p>Compendium page not generated yet.</p>',
            css_href=STYLE_HREF_CHAPTER,
            meta_title=f"{BOOK_TITLE} | 1. Singles",
        )
        comp.write_text(stub, encoding="utf-8")
        return

    idx = next((i for i, p in enumerate(pages) if p.kind == "singletons"), None)
    if idx is None:
        return
    prevp = pages[idx - 1] if idx > 0 else None
    nextp = pages[idx + 1] if idx + 1 < len(pages) else None
    nav = nav_bar(prevp, nextp, base_prefix="../")
    fnav = floating_nav(prevp, nextp, base_prefix="../")

    html = comp.read_text(encoding="utf-8")
    # If compendium was generated with its own nav, replace it; else inject at top/bottom.
    if '<nav class="book-nav">' in html:
        html = patch_nav_in_html(html, nav, nav)
        # Inject floating nav before </body>
        if 'class="float-nav' not in html:
            html = html.replace('</body>', f'{fnav}\n</body>')
    else:
        html = html.replace('<div class="page">', f'<div class="page">\n    {nav}', 1)
        # Inject bottom nav + floating nav before </body>
        html = html.replace('</body>', f'{nav}\n{fnav}\n</body>')
    comp.write_text(html, encoding="utf-8")


def maybe_run_cleanup(run_cleanup: bool):
    if not run_cleanup:
        print("Tweet text cleanup: skipped (use --run-cleanup to invoke).")
        return

    script = DATA_DIR / "tweet_text_cleanup.py"
    if not script.exists():
        raise SystemExit(f"Expected cleanup script not found: {script}")

    print(f"Tweet text cleanup: running {script} ...")
    subprocess.run(["python3", str(script)], check=True)


def ensure_dirs():
    BOOK_DIR.mkdir(parents=True, exist_ok=True)
    CHAPTERS_DIR.mkdir(parents=True, exist_ok=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-cleanup", action="store_true", help="Invoke data/tweet_text_cleanup.py before generating.")
    args = ap.parse_args()

    ensure_dirs()
    ensure_frontmatter_fragments()

    maybe_run_cleanup(args.run_cleanup)

    print(f"Loading selection from {SELECTION_JSON} ...")
    chapter_threads, _ = load_selection(SELECTION_JSON)
    print(f"Selected chapter threads: {len(chapter_threads)}")

    print(f"Loading threads from {THREADS_JSONL} ...")
    threads_by_id = load_threads(THREADS_JSONL)

    print(f"Loading tweets (with raw) from {TWEETS_JSONL} ...")
    tweets_by_id = load_tweets_raw(TWEETS_JSONL)

    print(f"Loading title overrides from {CHAPTER_TITLES_JSON} ...")
    title_overrides = load_chapter_title_overrides(CHAPTER_TITLES_JSON)

    # Load URL title map and overrides (for link anchor text and replacements)
    from tweet_text_cleanup import load_url_titles, load_url_overrides
    url_titles = load_url_titles()
    url_overrides = load_url_overrides()
    if url_titles:
        print(f"Loaded URL titles: {len(url_titles)} entries")
    else:
        print("No url_titles.json found; links will use display_url or 'link'.")
    if url_overrides:
        print(f"Loaded URL overrides: {len(url_overrides)} entries")

    pages = build_pages(chapter_threads, threads_by_id, tweets_by_id, title_overrides)

    # Generate outputs
    clear_old_thread_chapters()
    write_cover(pages)
    write_title_page(pages)
    write_toc(pages)
    write_preface_page(pages)
    patch_compendium_nav(pages)
    write_thread_chapters(pages, threads_by_id, tweets_by_id, url_titles=url_titles, url_overrides=url_overrides)

    print(f"Wrote cover: {COVER_OUT}")
    print(f"Wrote ToC: {TOC_OUT}")
    print(f"Wrote title: {TITLE_OUT}")
    print(f"Wrote preface: {PREFACE_OUT}")
    print(f"Patched/checked singletons: {CHAPTERS_DIR / 'compendium.html'}")


if __name__ == "__main__":
    main()
